services:
  mongo:
    image: mongo:6.0
    container_name: mongodb_aggregator
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  go-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api_aggregator
    restart: on-failure
    depends_on:
      - mongo
    env_file:
      - .env
    command: ["sh", "-c", "sleep 10 && ./app"] 

volumes:
  mongo_data: